title: Welcome to Aerie's Blog
author: AerieMinor
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog created with the help of GitHub, to ensure that I learn the essentials of GitHub and how to write great documentation,
  as well as make awesome contributions :smile:!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
